### PR TITLE
Added --all option to softirq-top to display all metrics from /proc/s…

### PR DESCRIPTION
**Pull request by vipulnayyar**
…oftirqs

### CODE REVIEW

**Comment by vipulnayyar** [comment]
Will update the PR with required corrections

**Comment by strizhechenko** [comment]
Hey hey, @vipulnayyar! I haven't looked at the code with attention to details yet (it's really hard to do without computer) but there are few failed tests in travis-ci output and new feature seems to work unconditionally. I'm on vacation for 4 more days, otherwise I would give much better feedback right now.

So, short todo list:
- [ ] fix the tests
  - [ ] utility softirq-top should be runnable at least with --help option
  - [ ] network-top utility should not be affected by changes, at least now. Useless --all given by softirqs module is not a problem to solve now (I'll fix it later somehow).
- [ ] split --all and normal behavior by checking the options.all in __repr__()
- [ ] there's no need to colorize anything except net_rx and net_tx
- [ ] there's no need to evaluate "hidden" metrics while working without --all option

Sorry for my late answer and thanks for contribution!

**Comment by strizhechenko** [comment]
You can send corrections step by step, I don't mind about few notifications and I'll try to help as soon as possible :)

**Comment by vipulnayyar** [comment]
Closing for now, bogged down with things. May reopen it again if it's still unsolved after a while. Thanks for the guidance.

**Comment by strizhechenko** [comment]
Thanks for a try.

**Pull request closed without merging**
