### PR TITLE
fix: incompatibilities with modern systems

### PR DESCRIPTION
**Pull request by rayrapetyan**
Fixed as many issues as I could find on a modern Debian 11 distro:

- lscpu output may contain ":" characters in values breaking yaml parser, e.g.:
```Vulnerability Mmio stale data:   Vulnerable: Clear CPU buffers attempted, no mic  rocode; SMT vulnerable```
- "RX:" entries may contain "n/a" (string values) breaking casting to int
- process.communicate() returns bytearray (at least in Python 3.9)
- `__repr_table__` in the `link-rate` tried to concat list with str producing an error.

### CODE REVIEW

**Comment by strizhechenko** [comment]
Oh wow, first pull request with actual bugfixes from stranger. I'll check it and merge few hours later. Thanks you a lot :)

**Comment by rayrapetyan** [comment]
Thanks, @strizhechenko. I would like to add tests for fixes in this PR, but before doing that, would you mind if we also: 1. Drop Python 2 support 2. Migrate to poetry. 3 Use tox for running tests 4. Add more linters?
I would create a separate PR for each of these.

**Comment by strizhechenko** [comment]
Hmm, I would say the development of the project is semi-frozen. I can't drop py2 support, but I think you may feel free to fork it as netutils-linux-ng and I'll mention it in readme.

**Comment by Znuff** [comment]
How come this hasn't still been merged in the mainline yet? It's been half a year, these changes don't seem to break anything (even py2 support).

Also, it's 2023, Py2 has been officially dead for 3 and half years. Most Distributions that had Py2 as "default" are reaching their EOL  (RHEL7-based ones, Ubuntu ~18 and lower, etc.)

**Comment by strizhechenko** [comment]
Well, it's complicated.

https://github.com/strizhechenko/netutils-linux/compare/db42e32..HEAD

**Pull request closed without merging**
